# Generated by Django 5.1.7 on 2025-05-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
