# Generated by Django 5.2 on 2025-05-05 06:11

import django.db.models.deletion
import savingsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('savings_account', models.CharField(default=savingsapp.models.account_no_generator, editable=False, max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledgers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsapp.accounts')),
            ],
        ),
    ]
